/* eslint-disable */
require('./about_yes')
require('./aboutme')
require('./eightball')
require('./email')
require('./logo')
require('./music')
require('./resume')
require('./skills')
require('./solitare')
require('./svg')
require('./threedee')
require('./top_logo')
require('./video')
